---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: bridge
    environment:
      - PUID=1000f
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-MevVUxfsGWnvs4gr4gze
    volumes:
      # - /mnt/media/Movies:/movies
      # - /mnt/media/Music:/music
      - /media/zonmei/YottaDisk11/media/Movies:/data/movies
      - /media/zonmei/YottaDisk11/media/Music:/data/music
      - /media/zonmei/YottaDisk11/media/Pictures:/data/Pictures
      - /media/zonmei/YottaDisk11/media/Books:/data/Books
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    # volumes:
      - /media/zonmei/YottaDisk11/configs/radarr:/config
      # - /media/zonmei/YottaDisk11/media/Movies:/data/movies
      - /media/zonmei/YottaDisk11/media/Movies:/data/movies
      # - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
      - UMASK_SET=022
    # volumes:
      - /media/zonmei/YottaDisk11/configs/sonarr:/config
      # - /srv/dev-disk-by-partuuid-0d4a201c-b292-412d-ade6-cc5561e54f1f/TV:/tv
      - /media/zonmei/YottaDisk21/Torrents:/data/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true   
    environment:
      - VPN_USERNAME=hc6ehIBg0oF1kku0
      - VPN_PASSWORD=SDQAo11LcPjja0N5C9TMovUsu32BXAZl
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT_ENV=8080
      - INCOMING_PORT_ENV=8999
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.1.0/24 #adjust this to YOUR network settings
      - NAME_SERVERS=1.1.1.1,1.0.0.1 #you can use whatever DNS provider you want
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - /media/zonmei/YottaDisk11/configs/QBittorrentVPN:/config
      - /media/zonmei/YottaDisk21/Torrents:/data/downloads
      - /etc/timezone:/etc/timezone:ro #This is for TimeZone
    restart: unless-stopped   

  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr
    restart: unless-stopped
    ports:
        - 90:80
    volumes:
        - /media/zonmei/YottaDisk11/configs/organizr:/config
        # - C:\Users\kirkb\Pictures:/config
    environment:
        - fpm=true #true or false | using true will provide better performance
        - branch=v2-master #v2-master or #v2-develop
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /media/zonmei/YottaDisk11/configs/jackett:/config
      - /media/zonmei/YottaDisk21/Torrents:/data/downloads
      # - C:\Users\kirkb\Pictures:/config
      # - C:\Users\kirkb\Downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    
## System Monitoring

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      environment:
        - PUID=998
        - PGID=100
        - TZ=America/New_York
        - UMASK_SET=022
      volumes:
        #- /srv/dev-disk-by-partuuid-0d4a201c-b292-412d-ade6-cc5561e54f1f/Configs/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./Configs/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - 9292:9090
      restart: unless-stopped  

  node-exporter:
      image: quay.io/prometheus/node-exporter:latest
      container_name: node-exporter
      network_mode: host
      environment:
        - PUID=998
        - PGID=100
        - TZ=America/New_York
        - UMASK_SET=022
      volumes:
        - /:/host:ro,rslave
      ports:
        - 9100:9090
      restart: unless-stopped    

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
      - UMASK_SET=022
    ports:
      - 3000:3000
    restart: unless-stopped          